export interface KqlKeyword {
    type: "keyword" | "function" | "table" | "field";
    description: string;
    body?: string;
}

export const kqlKeywords: Record<string, KqlKeyword> = {
    Timestamp: { type: "field", description: "Timestamp of the event" },
    print: { type: "field", description: "Outputs a single row with one or more scalar expressions", body: "print [ColumnName =] ScalarExpression [',' ...]" },
    ago: {
        type: "function",
        description: "Returns the time offset relative to the time the query executes. For example, `ago(1h)` is one hour before the current clock's reading",
        body: "ago(a_timespan)",
    },
    EmailEvents: { type: "table", description: "Email address associated with the event" },
    IdentityLogonEvents: { type: "table", description: "Table storing logon events for identities" },
    IdentityQueryEvents: { type: "table", description: "Table storing identity query events" },
    IdentityDirectoryEvents: { type: "table", description: "Table storing changes in identity directories" },
    DeviceProcessEvents: { type: "table", description: "Table storing process creation and termination events on devices" },
    DeviceNetworkEvents: { type: "table", description: "Table storing network activity events from devices" },
    DeviceFileEvents: { type: "table", description: "Table storing file creation, modification, and deletion events" },
    DeviceRegistryEvents: { type: "table", description: "Table storing registry changes on devices" },
    DeviceLogonEvents: { type: "table", description: "Table storing device logon and logoff events" },
    DeviceImageLoadEvents: { type: "table", description: "Table storing loaded executable or DLL images on devices" },
    DeviceEvents: { type: "table", description: "Table storing general device events" },
    BehaviorEntities: { type: "table", description: "Table storing entities related to detected behaviors" },
    range: { type: "keyword", description: "Generates a table with an arithmetic series of values", body: "range columnName from start to stop step step" },
    invoke: { type: "keyword", description: "Runs the function on the table that it receives as input", body: "T | invoke function([param1, param2])" },
    evaluate: {
        type: "keyword",
        description: "Evaluates query language extensions (plugins)",
        body: "[T |] evaluate [ evaluateParameters ] PluginName ( [PluginArg1 [, PluginArg2]... )",
    },
    lookup: {
        type: "keyword",
        description: "Extends the columns of a fact table with values looked-up in a dimension table",
        body: "T1 | lookup [kind = (leftouter|inner)] ( T2 ) on Attributes",
    },
    let: {
        type: "keyword",
        description:
            "Binds a name to expressions that can refer to its bound value. Values can be lambda expressions to create query-defined functions as part of the query. Use `let` to create expressions over tables whose results look like a new table",
        body: "let Name = ScalarExpression | TabularExpression | FunctionDefinitionExpression",
    },
    where: { type: "keyword", description: "Filters on a specific predicate", body: "T | where Predicate" },
    summarize: {
        type: "keyword",
        description: "Groups the rows according to the `by` group columns, and calculates aggregations over each group",
        body: "T | summarize [[Column =] Aggregation [, ...]] [by [Column =] GroupExpression [, ...]]",
    },
    project: {
        type: "keyword",
        description: "Selects the columns to include in the order specified",
        body: "T | project ColumnName [= Expression] [, ...] Or T | project [ColumnName | (ColumnName[,]) =] Expression [, ...]",
    },
    "project-away": {
        type: "keyword",
        description: "Selects the columns to exclude from the output",
        body: "T | project-away ColumnNameOrPattern [, ...]",
    },
    "project-keep": {
        type: "keyword",
        description: "Selects the columns to keep in the output",
        body: "T | project-keep ColumnNameOrPattern [, ...]",
    },
    "project-rename": {
        type: "keyword",
        description: "Renames columns in the result output",
        body: "T | project-rename new_column_name = column_name",
    },
    "project-reorder": {
        type: "keyword",
        description: "Reorders columns in the result output",
        body: "T | project-reorder Col2, Col1, Col* asc",
    },
    extend: {
        type: "keyword",
        description: "Creates a calculated column and adds it to the result set",
        body: "T | extend [ColumnName | (ColumnName[, ...]) =] Expression [, ...]",
    },
    join: {
        type: "keyword",
        description:
            "Merges the rows of two tables to form a new table by matching values of the specified column(s) from each table. Supports a full range of join types: `fullouter`, `inner`, `innerunique`, `leftanti`, `leftantisemi`, `leftouter`, `leftsemi`, `rightanti`, `rightantisemi`, `rightouter`, `rightsemi`",
        body: "LeftTable | join [JoinParameters] ( RightTable ) on Attributes",
    },
    union: { type: "keyword", description: "Takes two or more tables and returns all their rows", body: "[T1] | union [T2], [T3], …" },
    top: {
        type: "keyword",
        description: "Returns the first N rows of the dataset when the dataset is sorted using `by`",
        body: "T | top numberOfRows by expression [asc|desc] [nulls first|last]",
    },
    order: { type: "keyword", description: "Sort rows by a column" },
    sort: {
        type: "keyword",
        description: "Sort the rows of the input table by one or more columns in ascending or descending order",
        body: "T | sort by expression1 [asc|desc], expression2 [asc|desc], …",
    },
    render: {
        type: "keyword",
        description: "Renders results as a graphical output",
        body: "T | render Visualization [with (PropertyName = PropertyValue [, ...] )]",
    },
    "mv-expand": { type: "keyword", description: "Turns dynamic arrays into rows (multi-value expansion)", body: "T | mv-expand Column" },
    make_set: { type: "function", description: "Aggregate values into a dynamic array", body: "make_set(${1:ColumnName})" },
    count: {
        type: "function",
        description: `Counts records in the input table (for example, T). This operator is shorthand for \`summarize count()\``,
        body: "T | count",
    },
    countif: { type: "function", description: "Count rows that meet a condition", body: "countif()" },
    AlertEvents: { type: "table", description: "Table storing security alert events" },
    DeviceName: { type: "field", description: "Name of the endpoint device" },
    FileName: { type: "field", description: "File involved in the event" },
    InitiatingProcessFileName: { type: "field", description: "File name of the process that triggered the event" },
    ReportId: { type: "field", description: "Unique identifier for the report" },
    TimeGenerated: { type: "field", description: "Timestamp when the event occurred" },
    RemoteIP: { type: "field", description: "IP address of the remote endpoint" },
    RemoteUrl: { type: "field", description: "URL of the remote endpoint or request" },
    RemoteIPCountry: { type: "field", description: "Country of the remote IP address" },
    IPAddress: { type: "field", description: "IP address involved in the event" },
    AccountName: { type: "field", description: "User account associated with the event" },
    ActionType: { type: "field", description: "Type of action performed (e.g., file creation, process start)" },
    AlertSeverity: { type: "field", description: "Severity level of a security alert" },
    EventID: { type: "field", description: "Unique identifier for the event type" },
    DeviceType: { type: "field", description: "Type of the device (e.g., server, workstation, mobile)" },
    AccountDomain: { type: "field", description: "Domain of the user account" },
    iif: { type: "function", description: "Inline if statement for conditional logic", body: "iif(condition, trueValue, falseValue)" },
    case: {
        type: "function",
        description: "Adds a condition statement, similar to if/then/elseif in other systems",
        body: "case(predicate_1, then_1, predicate_2, then_2, predicate_3, then_3, else)",
    },
    parse: {
        type: "keyword",
        description: "Evaluates a string expression and parses its value into one or more calculated columns. Use for structuring unstructured data",
        body: "T | parse [kind=regex [flags=regex_flags] |simple|relaxed] Expression with * (StringConstant ColumnName [: ColumnType]) *...",
    },
    parse_json: { type: "function", description: "Parse JSON string into a structured object", body: "parse_json(ColumnName)" },
    parse_csv: { type: "function", description: "Parse CSV formatted string into columns", body: "parse_csv(ColumnName)" },
    distinct: {
        type: "keyword",
        description: "Produces a table with the distinct combination of the provided columns of the input table",
        body: "distinct [ColumnName], [ColumnName]",
    },
    "make-series": {
        type: "function",
        description: "Creates series of specified aggregated values along a specified axis",
        body: "T | make-series [MakeSeriesParamters] [Column =] Aggregation [default = DefaultValue] [, ...] on AxisColumn from start to end step step [by [Column =] GroupExpression [, ...]]",
    },
    moving_avg: { type: "function", description: "Compute moving average over time series", body: "moving_avg(ColumnName, interval)" },
    substring: { type: "function", description: "Extract a substring from a column", body: "substring(ColumnName, start, length)" },
    format_datetime: { type: "function", description: "Returns data in various date formats", body: "format_datetime(datetime , format)" },
    bin: { type: "function", description: "Rounds all values in a timeframe and groups them", body: "bin(value,roundTo)" },
    search: {
        type: "keyword",
        description: "Searches all columns in the table for the value",
        body: "[TabularSource |] search [kind=CaseSensitivity] [in (TableSources)] SearchPredicate",
    },
    take: {
        type: "keyword",
        description: `Returns the specified number of records. Use to test a query **Note**: \`take\` and \`limit\` are synonyms`,
        body: "T | take NumberOfRows",
    },
    contains: { type: "keyword", description: "Looks for any substring match", body: "T | where col1 contains/has [search term]" },
    has: { type: "keyword", description: "Looks for a specific word (better performance)", body: "T | where col1 ${1|contains,has|} [search term]" },
    startswith: { type: "function", description: "Filter rows where a column starts with a value", body: "ColumnName startswith 'value'" },
    in: { type: "function", description: "Filter rows where a column matches one of a list of values", body: "ColumnName in ('value1', 'value2')" },
    between: { type: "function", description: "Filter rows where a column is between two values", body: "ColumnName between (start, end)" },
    datetime: { type: "function", description: "Manipulate or extract datetime values", body: "datetime('YYYY-MM-DD hh:mm:ss')" },
    datetime_diff: { type: "function", description: "Compute difference between two datetime columns", body: "datetime_diff(Column1, Column2)" },
    round: { type: "function", description: "Round numeric values to specified decimals", body: "round(ColumnName, decimals)" },
    substringof: { type: "function", description: "Check if substring exists in a string", body: "substringof('value', ColumnName)" },
    externaldata: { type: "function", description: "Import external data from files or URLs", body: "externaldata(Column1:Type1, Column2:Type2) [with (...)]" },
    "render table": { type: "keyword", description: "Render the query results as a table" },
    "render timechart": { type: "keyword", description: "Render the results as a time chart" },
    "render barchart": { type: "keyword", description: "Render the results as a bar chart" },
    "render piechart": { type: "keyword", description: "Render the results as a pie chart" },
    "render columnchart": { type: "keyword", description: "Render the results as a column chart" },
    asc: { type: "keyword", description: "Sort column in ascending order" },
    desc: { type: "keyword", description: "Sort column in descending order" },
};
